//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYESW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrdersId { get; set; }
        public Nullable<int> UserId1 { get; set; }
        public Nullable<int> UserId2 { get; set; }
        public Nullable<int> GoodsId { get; set; }
        public Nullable<int> IsState { get; set; }
        public string Wuliu { get; set; }
        public Nullable<System.DateTime> BuyTime1 { get; set; }
        public Nullable<System.DateTime> BuyTime2 { get; set; }
        public Nullable<System.DateTime> BuyTime3 { get; set; }
        public Nullable<System.DateTime> BuyTime4 { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
    }
}
