//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYESW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pingjia_texts
    {
        public int Pingjia_textsId { get; set; }
        public Nullable<int> TextsId { get; set; }
        public Nullable<int> GoodsId { get; set; }
        public Nullable<int> States { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Texts Texts { get; set; }
    }
}
