//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYESW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealName
    {
        public int RealNameId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IdCard { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> IsDelete { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
