//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYESW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Texts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Texts()
        {
            this.Friends_texts = new HashSet<Friends_texts>();
            this.HuDong_texts = new HashSet<HuDong_texts>();
            this.Pingjia_texts = new HashSet<Pingjia_texts>();
        }
    
        public int TextsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Textbody { get; set; }
        public Nullable<System.DateTime> addTiem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friends_texts> Friends_texts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HuDong_texts> HuDong_texts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pingjia_texts> Pingjia_texts { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
