//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYESW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeiGui
    {
        public int WeiGuiId { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public string a_1 { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string type_1 { get; set; }
        public Nullable<int> GLuser { get; set; }
        public Nullable<int> UserId1 { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
    }
}
